Fix arch
Saffica/developerHelper pull request #5
Opened 2023-07-20 22:38 UTC by Saffica

2023-07-21 09:25 UTC, Gr0ks requested changes

2023-07-21 09:25 UTC, Gr0ks commented on internal/config/config.go
> +	validator := NewValidator(cfg)
не понимаю почему только 1 переменную валидируешь.
если делаешь валидацию то тут есть 2 подхода:
1. через геттеры для каждого значения и внутри них делать валидацию
2. валидировать получаемые значения по месту использования

2023-07-21 09:25 UTC, Gr0ks commented on internal/config/config.go
> +	cfg.SetDefault("cfg.path", "./configs/config.json")
данное дефолтное значение для пути можно перенести в конструктор и подставлять в этом методе из поля и тогда легко будет тестировать

2023-07-21 09:25 UTC, Gr0ks commented on main/app.go
> +package main
не понятно что это за пакет

2023-07-21 09:25 UTC, Gr0ks commented on main.go
>  	vcs, err := vcsrepository.FindByLocalPackID(cfg.GetString("LOCAL_PACK_ID"))
для того чтоб не передавать значение из конфига ты в конструктор передал сам конфиг и данное значение внутри метода можешь получить

2023-07-21 10:29 UTC, Saffica commented on main/app.go
> +package main
в ночном потоке добавил)) удалил

2023-07-21 10:29 UTC, Saffica commented on main.go
>  	vcs, err := vcsrepository.FindByLocalPackID(cfg.GetString("LOCAL_PACK_ID"))
перенёс

2023-07-21 10:30 UTC, Saffica commented on internal/config/config.go
> +	cfg.SetDefault("cfg.path", "./configs/config.json")
перенёс

2023-07-21 10:30 UTC, Saffica commented on internal/config/config.go
> +	validator := NewValidator(cfg)
переделал

2023-07-22 20:59 UTC, Gr0ks requested changes

2023-07-22 20:59 UTC, Gr0ks commented on .gitignore
> +configs/config.json
если оригинальный конфиг в гитигноре  добавь configs/config-example.json

2023-07-22 20:59 UTC, Gr0ks commented on internal/config/config.go
> +func New() *cfg {
передавай дефолтный путь параметром в конструктор, тогда все по феншую будет)

2023-07-22 22:20 UTC, Saffica commented on .gitignore
> +configs/config.json
Тогда в инструкцию надо добавлять ренейм файла? Я его закинул в гитигнор, потому что каждый раз забываю обезличить конфиг)

2023-07-22 22:27 UTC, Saffica commented on internal/config/config.go
> +func New() *cfg {
исправил

2023-07-23 10:25 UTC, Gr0ks commented on .gitignore
> +configs/config.json
ну или в ридми добавить пример конфига, просто не увидел тут изменения в ридми и не понял откуда пользователь может узнать какой конфиг нужно подсовывать, сам файл конфига в гитигноре и если он поменяется то в репозитории это не отразиться, это может привести к ошибкам в будущем.
обычно такие файлы располагают там же где и основной конфиг и называют config-example.json или .env.example в зависимости от пакета который подтягивает эти значения в код

2023-07-23 10:25 UTC, Gr0ks approved these changes

2023-07-24 07:27 UTC, merged